# Builds and publishes the documentation website to gh-pages branch
name: Build documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: build
  cancel-in-progress: true
permissions:
  # Both required by actions/deploy-pages
  pages: write
  id-token: write

jobs:
  build:
    name: Build documentation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Build documentation
        run: dotnet docfx docfx.json

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        continue-on-error: ${{vars.IS_CANONICAL_DOCS_REPO != 'true'}}
        uses: actions/deploy-pages@v4
